# Generated by Django 3.2 on 2021-04-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='grams',
            field=models.FloatField(default=100.0),
        ),
    ]
