# Generated by Django 3.2 on 2021-04-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcal', '0004_food_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('jedzenie', 'food'), ('napój', 'drink')], default='unconfirmed', max_length=40),
        ),
    ]
