# Generated by Django 3.2 on 2021-04-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcal', '0005_alter_food_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='DrinkOrFood',
            field=models.CharField(choices=[('jedzenie', 'food'), ('napój', 'drink')], default='unconfirmed', max_length=40),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('unconfirmed', 'Waiting for confirmed'), ('confirmed', 'Accepted'), ('rejected', 'Rejected')], default='unconfirmed', max_length=40),
        ),
    ]
