# Generated by Django 3.2 on 2021-04-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kcal', '0006_auto_20210425_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='DrinkOrFood',
        ),
    ]
