# Generated by Django 3.2 on 2021-04-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcal', '0007_remove_food_drinkorfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='DrinkOrFood',
            field=models.CharField(choices=[('jedzenie', 'food'), ('napój', 'drink')], default='jedzenie', max_length=40),
        ),
    ]
